name = "AstroIC"
uuid = "5b3ca070-48c3-41ea-b469-89825dd01fde"
version = "0.1.4"
authors = ["islent <leoislent@gmail.com>"]

[deps]
AstroIO = "c85a633c-0c3f-44a2-bffe-7f9d0681b3e7"
AstroLib = "c7932e45-9af1-51e7-9da9-f004cd3a462b"
AstroSimBase = "c6a34d98-f626-4d8d-b450-a3f124eaada6"
BangBang = "198e06fe-97b7-11e9-32a5-e1d131e6ad66"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
PhysicalParticles = "78724250-4eb2-11e9-0f34-13a7aab864c5"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAngles = "6fb2a4bd-7999-5318-a3b2-8ad61056cd98"
UnitfulAstro = "6112ee07-acf9-5e0f-b108-d242c714bf9f"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
AstroIO = "0.1"
AstroLib = "0.4"
AstroSimBase = "0.1"
BangBang = "0.3, 0.4, 0.5"
CSV = "0.10"
DataFrames = "1"
Dierckx = "0.5"
Distributions = "0.25"
DocStringExtensions = "0.8, 0.9"
Measurements = "2"
Optim = "1, 2"
PhysicalConstants = "0.2"
PhysicalParticles = "1"
PrecompileTools = "1"
QuadGK = "2"
Reexport = "1"
StructArrays = "0.6, 0.7"
Unitful = "1"
UnitfulAngles = "0.7"
UnitfulAstro = "1"
XLSX = "0.10"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
